name = "subscription-converter"
main = "src/index.js"
compatibility_date = "2024-06-30"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[build]
command = ""
